### PR TITLE
Fix incorrect usage of getValue() on a field

### LINKED ISSUE #19: Fix usage of $user->get('password_enhancements_password_change_required')->getValue()
`$user->get('password_enhancements_password_change_required')->getValue()` may returns an empty array.

### PR DESCRIPTION
**Pull request by mxr576**
Closes #19

### CODE REVIEW

File: src/Access/AccessControlHandler.php [hunk 1]
```diff
@@ -77,7 +77,8 @@ public static function create(ContainerInterface $container) {
   public function hasPasswordChangeAccess(AccountInterface $current_user): AccessResultInterface {
     /** @var \Drupal\user\UserInterface $user */
     $user = $this->userStorage->load($current_user->id());
-    return AccessResult::allowedIf($user->get('password_enhancements_password_change_required')->getValue()[0]['value']);
+    $is_password_change_required = $user->get('password_enhancements_password_change_required')->getValue() ? (bool) $user->get('password_enhancements_password_change_required')->getValue()[0]['value'] : FALSE;
+    return AccessResult::allowedIf($is_password_change_required);
```
Comment (tamasd) [inline src/Access/AccessControlHandler.php:81]: Shouldn't this be `AccessResult::forbiddenIf(!$is_password_change_required)`?

**Review by tamasd — CHANGES_REQUESTED** [review]

File: src/Access/AccessControlHandler.php (hunk 1 above)
Comment (mxr576) [reply src/Access/AccessControlHandler.php:81]: Not sure yet, in this PR I only wanted to fix the logic that causes WSOD. We'll see later, probably using `allowedIf` is fine because it only controls access to the `PasswordChangeForm`.

Comment (tamasd) [reply src/Access/AccessControlHandler.php:81]: Ok

**Review by tamasd — APPROVED** [review]
